name: appicons
description: A new Flutter project with custom app icon and splash screen

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter_icons:
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon_foreground.png" # only available for Android 8.0 devices and above
  adaptive_icon_background: "#196bc8"
  android: true
  ios: true

flutter_native_splash:
  image: assets/logo.png
  color: "#196bc8"
  android_12:
    image: assets/icon_foreground.png
    color: "#196bc8"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.8

flutter:
  uses-material-design: true
